### ISSUE TITLE
flex布局

### ISSUE THREAD

**Issue by JScheng** [JScheng/blog#3]
## 前言
弹性盒子布局，相较于传统布局方式(盒子模型)可以快速实现，具有更好的灵活度，特别适合应用于组件和小规模的布局。  
### 浏览器的支持情况
目前普遍应用于移动端开发。  
![1](https://github.com/JScheng/blog/raw/master/images/3/1.png)  
### 概念
flexbox 布局主要思想是让容器有能力让其子项目能够改变其宽度、高度(甚至顺序)，以最佳方式填充可用空间（主要是为了适应所有类型的显示设备和屏幕大小）。Flex 容器会使子项目（伸缩项目）扩展来填满可用空间，或缩小他们以防止溢出容器。  
任何容器都可以指定为Flex布局，包括行内元素。  
设置为 `display:flex` 或 `display:inline-flex` 的元素称为伸缩容器。  
Webkit 内核的浏览器，必须加上`-webkit`前缀。  
**注意**，设为 Flex 布局以后，子元素的float、clear和vertical-align属性将失效。  
![1](https://github.com/JScheng/blog/raw/master/images/3/flexbox.png)  
主轴(main axis)：开始位置为`main start`，结束位置`main end`，项目占据主轴的空间`main size`。  
交叉轴(cross axis)：开始位置为`cross start`，结束位置`cross end`，项目占据交叉在的空间`main size`。  
### 容器的属性
![1](https://github.com/JScheng/blog/raw/master/images/3/flex-container.png) 
### display
使用display指定伸缩容器;
```css
.container {
  display: flex; /* or inline-flex */
}
```
### flex-direction
使用flex-direction指定主轴的方向;
```css
.container {
  flex-direction: row | row-reverse | column | column-reverse;
}
```
![1](https://github.com/JScheng/blog/raw/master/images/3/2.png)  

`row`：（默认值），水平方向伸缩，伸缩项目从左向右排列。  
`row-reverse`：水平方向伸缩，伸缩项目从右向左排列。  
`column`：垂直方向伸缩，伸缩项目从上往下。  
`column-reverse`：垂直方向伸缩，伸缩项目从下往上。  

### flex-wrap
flex-wrap默认情况下，项目排在一条轴线上。 如果轴线排不下可以换行。  
![1](https://github.com/JScheng/blog/raw/master/images/3/3.png)  
```css
.container{
  flex-wrap: nowrap | wrap | wrap-reverse;
}
```

`nowrap`：（默认值），在一条轴上不换行。  
`wrap`：换行，第一行从上面开始。  
`wrap-reverse`：换行，第一行从下面开始。   

关于flex-wrap的实例：  
html：  
```html
<ul class="flex-container nowrap">
  <li class="flex-item">1</li>
  <li class="flex-item">2</li>
  <li class="flex-item">3</li>
  <li class="flex-item">4</li>
  <li class="flex-item">5</li>
  <li class="flex-item">6</li>
  <li class="flex-item">7</li>
  <li class="flex-item">8</li>
</ul>

<ul class="flex-container wrap">
  <li class="flex-item">1</li>
  <li class="flex-item">2</li>
  <li class="flex-item">3</li>
  <li class="flex-item">4</li>
  <li class="flex-item">5</li>
  <li class="flex-item">6</li>
  <li class="flex-item">7</li>
  <li class="flex-item">8</li>
</ul>

<ul class="flex-container wrap-reverse">
  <li class="flex-item">1</li>
  <li class="flex-item">2</li>
  <li class="flex-item">3</li>
  <li class="flex-item">4</li>
  <li class="flex-item">5</li>
  <li class="flex-item">6</li>
  <li class="flex-item">7</li>
  <li class="flex-item">8</li>
</ul>
```
css：  
```css
.flex-container {
  padding: 0;
  margin: 0;
  list-style: none;
  border: 1px solid silver;
  -ms-box-orient: horizontal;
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -moz-flex;
  display: -webkit-flex;
  display: flex;
}

.nowrap  { 
  -webkit-flex-wrap: nowrap;
  flex-wrap: nowrap;
}

.wrap { 
  -webkit-flex-wrap: wrap;
  flex-wrap: wrap;
}  
.wrap li {
  background: gold;
}

.wrap-reverse { 
  -webkit-flex-wrap: wrap-reverse;
  flex-wrap: wrap-reverse;
}  
.wrap-reverse li {
  background: deepskyblue;
}

.flex-item {
  background: tomato;
  padding: 5px;
  width: 100px;
  height: 100px;
  margin: 10px;
  
  line-height: 100px;
  color: white;
  font-weight: bold;
  font-size: 2em;
  text-align: center;
}
```
result：  
![1](https://github.com/JScheng/blog/raw/master/images/3/4.png)  

### flex-flow
flex-flow属性是`flex-direction`和`flex-wrap`的简写形式。  默认值：`row nowrap`
```css
.container {
  flex-flow: <flex-direction> || <flex-wrap>;
}
```
### justify-content
justify-content属性定义项目在主轴上的对齐方式。  
```css
.container {
  justify-content: flex-start | flex-end | center | space-between | space-around;
}
```
![1](https://github.com/JScheng/blog/raw/master/images/3/5.png)  
假设主轴是从左到右的情况下：  
`flex-start`：(默认值)项目左对齐。  
`flex-end`：项目右对齐。  
`center`：项目居中对齐。  
`space-between`：项目两端对齐，项目之间的间隔相等。  
`space-around`：每个项目两侧间隔相等。  
### align-items
align-item属性定义交叉轴的对齐方式。  
```css
.container {
  align-items: flex-start | flex-end | center | baseline | stretch;
}
```
假设主轴是从上到下的情况下：  
`flex-start`：交叉轴的起点对齐。  
`flex-end`：交叉轴的终点对齐。  
`center`：交叉轴的终点对齐。  
`baseline`：项目第一行文字的基线对齐。    
`stretch`：(默认值)如果项目未设置高度或者设置为auto，将占满整个容器的高度。    
### align-content
align-content属性定义多根轴线的对齐方式，单个轴线不起作用。  
```css
.container {
  align-content: flex-start | flex-end | center | space-between | space-around | stretch;
}
```
![1](https://github.com/JScheng/blog/raw/master/images/3/6.png)  
`flex-start`：交叉轴起点对齐。  
`flex-end`：交叉轴终点对齐。  
`center`：交叉轴中点对齐。  
`space-between`：交叉轴两端对齐，轴线之间间隔平均分布。  
`space-around`：每根轴线两侧的间隔都相等。  
`stretch`：轴线占满整个交叉轴。  

**容器的属性总结**：容器总共有7个属性：`display`,`flex-direction`,`flex-wrap`,`flex-flow`,`justify-content`,`align-items`,`align-content`。  

### 项目的属性
![1](https://github.com/JScheng/blog/raw/master/images/3/flex-items.png)   

### order
order属性定义项目的排列顺序，数值越小排列越靠前，默认为0。  
```css
.item {
  order: <integer>;
}
```
![1](https://github.com/JScheng/blog/raw/master/images/3/7.png)  

### flex-grow
`flex-grow`属性定义项目的放大比例，默认为0，即如果存在剩余空间，也不放大。
```css
.item {
  flex-grow: <number>; /* default 0 */
}
```
![1](https://github.com/JScheng/blog/raw/master/images/3/8.png)  
设置负数无效，如果项目中有一个为2，其余为1，则剩余空间中2所占的比例是其余项目的2倍。  

### flex-shrink
`flex-shrink`属性定义了项目的缩小比例，默认为1，即空间不足项目将缩小。  
```css
.item {
  flex-shrink: <number>; /* default 1 */
}
```
![1](https://github.com/JScheng/blog/raw/master/images/3/9.png)  

### flex-basis
`flex-basis`属性定义占据主轴空间，默认值为auto，即项目本来的大小。  
```css
.item {
  flex-basis: <length> | auto; /* default auto */
}
```

### flex
`flex`属性是`flex-grow`，`flex-shrink`，和`flex-basis`的简写，默认值为`0 1 auto`，后两个属性可选。  
```css
.item {
  flex: none | [ <'flex-grow'> <'flex-shrink'>? || <'flex-basis'> ]
}
```
该属性有两个快捷值：`auto (1 1 auto)` 和 `none (0 0 auto)`。  
 ### align-self
 `align-self`属性允许单个项目有与其他项目在交叉轴上不一样的对齐方式，覆盖`align-items`属性，默认值为auto。  
 如果没有父元素，则等同于`stretch`。  
 ```css
 .item {
  align-self: auto | flex-start | flex-end | center | baseline | stretch;
}
 ```
![1](https://github.com/JScheng/blog/raw/master/images/3/10.png)  

**项目的属性总结**：容器总共有6个属性：`order`,`flex-grow`,`flex-shrink`,`flex-basis`,`flex`,`align-self`。  

### 相关衔接：  
[A Complete Guide to Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)  
[Flex 布局教程：语法篇](http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)  
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/flex)

**Comment by JScheng** [comment]
## 前言
弹性盒子布局，相较于传统布局方式(盒子模型)可以快速实现，具有更好的灵活度，特别适合应用于组件和小规模的布局。  
### 浏览器的支持情况
目前普遍应用于移动端开发。  
![1](https://github.com/JScheng/blog/raw/master/images/3/1.png)  
### 概念
flexbox 布局主要思想是让容器有能力让其子项目能够改变其宽度、高度(甚至顺序)，以最佳方式填充可用空间（主要是为了适应所有类型的显示设备和屏幕大小）。Flex 容器会使子项目（伸缩项目）扩展来填满可用空间，或缩小他们以防止溢出容器。  
任何容器都可以指定为Flex布局，包括行内元素。  
设置为 `display:flex` 或 `display:inline-flex` 的元素称为伸缩容器。  
Webkit 内核的浏览器，必须加上`-webkit`前缀。  
**注意**，设为 Flex 布局以后，子元素的float、clear和vertical-align属性将失效。  
![1](https://github.com/JScheng/blog/raw/master/images/3/flexbox.png)  
主轴(main axis)：开始位置为`main start`，结束位置`main end`，项目占据主轴的空间`main size`。  
交叉轴(cross axis)：开始位置为`cross start`，结束位置`cross end`，项目占据交叉在的空间`main size`。  
### 容器的属性
![1](https://github.com/JScheng/blog/raw/master/images/3/flex-container.png) 
#### display
使用display指定伸缩容器;
```css
.container {
  display: flex; /* or inline-flex */
}
```
#### flex-direction
使用flex-direction指定主轴的方向;
```css
.container {
  flex-direction: row | row-reverse | column | column-reverse;
}
```
![1](https://github.com/JScheng/blog/raw/master/images/3/2.png)  

`row`：（默认值），水平方向伸缩，伸缩项目从左向右排列。  
`row-reverse`：水平方向伸缩，伸缩项目从右向左排列。  
`column`：垂直方向伸缩，伸缩项目从上往下。  
`column-reverse`：垂直方向伸缩，伸缩项目从下往上。  

### 项目的属性
![1](https://github.com/JScheng/blog/raw/master/images/3/flex-items.png)
